# Generated by Django 6.0.6 on 2026-08-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0005_remove_assettype_redundant_indexes"),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
        migrations.AddField(
            model_name="assetservice",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
        migrations.AddField(
            model_name="externalinventory",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
        migrations.AddField(
            model_name="rma",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="users.owner"
            ),
        ),
    ]
