# Generated by Django 6.0.6 on 2026-08-06 06:14

from django.db import migrations, models
from django.db.models.functions import Length

# Models whose description column narrows from 255 to 200 below, inherited from
# NetBox's PrimaryModel.
NARROWED_DESCRIPTION_MODELS = ("asset", "assetservice", "contract", "contractor", "invoice")

MAX_DESCRIPTION_LENGTH = 200

# Enough rows to see the pattern without burying the instructions
MAX_REPORTED_ROWS = 20


class DescriptionTooLongError(RuntimeError):
    """Raised instead of letting PostgreSQL abort halfway through the schema change."""


def build_report(problems):
    """Turn [(model_name, pk, length), ...] into an operator-facing error message."""
    listed = "\n".join(
        f"  {model_name} pk={pk} ({length} characters)" for model_name, pk, length in problems[:MAX_REPORTED_ROWS]
    )
    remainder = len(problems) - MAX_REPORTED_ROWS
    if remainder > 0:
        listed += f"\n  ... and {remainder} more"

    return (
        f"\n\n{len(problems)} description value(s) exceed the new {MAX_DESCRIPTION_LENGTH}-character limit.\n"
        f"Nothing has been changed -- this migration rolled back before altering any column, and\n"
        f"no description was shortened.\n\n"
        f"{listed}\n\n"
        f"Shorten each one by hand, then re-run migrate. In nbshell:\n\n"
        f"  from inventory_monitor.models import Asset\n"
        f"  obj = Asset.objects.get(pk=...)\n"
        f"  print(obj.description)   # decide what to keep; the rest can go in obj.comments\n"
        f"  obj.description = obj.description[:{MAX_DESCRIPTION_LENGTH}]\n"
        f"  obj.save()\n"
    )


def check_description_lengths(apps, schema_editor):
    """
    Refuse to narrow description from 255 to 200 while any row would lose characters.

    Without this guard the AlterField operations below fail with PostgreSQL's "value too
    long for type character varying(200)" -- after 0006 has already committed, and with no
    indication of which rows are at fault. Raising here instead rolls back the whole of
    0007 (migrations are atomic on PostgreSQL) and names every offending row.

    Truncating automatically was considered and rejected: the discarded characters are
    unrecoverable, and only the operator can judge what the description should say.
    """
    problems = []
    for model_name in NARROWED_DESCRIPTION_MODELS:
        rows = (
            apps.get_model("inventory_monitor", model_name)
            .objects.annotate(_description_length=Length("description"))
            .filter(_description_length__gt=MAX_DESCRIPTION_LENGTH)
            .order_by("pk")
            .values_list("pk", "_description_length")
        )
        problems.extend((model_name, pk, length) for pk, length in rows)

    if problems:
        raise DescriptionTooLongError(build_report(problems))


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0006_asset_owner_assetservice_owner_contract_owner_and_more"),
    ]

    operations = [
        migrations.RunPython(check_description_lengths, migrations.RunPython.noop),
        migrations.AddField(
            model_name="externalinventory",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="externalinventory",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="rma",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rma",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="asset",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="assetservice",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contract",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
