# Generated by Django 6.0.6 on 2026-08-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0006_asset_owner_assetservice_owner_contract_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalinventory",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="externalinventory",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="rma",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rma",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="asset",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="assetservice",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contract",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
