# Generated by Django 6.1 on 2026-09-04 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0007_externalinventory_comments_and_more"),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="users.owner"
            ),
        ),
        migrations.AlterField(
            model_name="assetservice",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="users.owner"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="users.owner"
            ),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="users.owner"
            ),
        ),
        migrations.AlterField(
            model_name="externalinventory",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="users.owner"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="users.owner"
            ),
        ),
        migrations.AlterField(
            model_name="rma",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="users.owner"
            ),
        ),
    ]
